--from tenant db
SELECT SERVICE_NAME, PORT, SQL_PORT, (PORT + 2) HTTP_PORT 
 FROM SYS.M_SERVICES 
 WHERE ((SERVICE_NAME='indexserver' and COORDINATOR_TYPE= 'MASTER') or (SERVICE_NAME='xsengine'))

--from system db
SELECT DATABASE_NAME, SERVICE_NAME, PORT, SQL_PORT, (PORT + 2) HTTP_PORT
 FROM SYS_DATABASES.M_SERVICES
 WHERE DATABASE_NAME='<tenant>' and
       ((SERVICE_NAME='indexserver' and COORDINATOR_TYPE= 'MASTER') or (SERVICE_NAME='xsengine'))
